#!/bin/bash

cp ~/quicklisp/local-projects/hackathon/build/* .
cp -ru ~/quicklisp/local-projects/hackathon/build/images .
cp -ru ~/quicklisp/local-projects/hackathon/build/includes .

git commit -a -m "update"
git push origin
