#!/bin/bash

cp ~/quicklisp/local-projects/hackathon/build/* .
rm -rf images includes
cp -r ~/quicklisp/local-projects/hackathon/build/images .
cp -r ~/quicklisp/local-projects/hackathon/build/includes .

git commit -a -m "update"
git push origin
